FORMAT: 1A
# GoBarber
Description
- Documentation of the Backend from aplication GoBarber.
- Tests can be realized on Insomnia or other aplications for API's test

<!-- include(user.apib) -->
<!-- include(session.apib) -->
<!-- include(files.apib) -->
<!-- include(providers.apib) -->
<!-- include(appointments.apib) -->
<!-- include(schedule.apib) -->
<!-- include(notification.apib) -->
<!-- include(avaiable.apib) -->
